import Foundation
import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Workspace",
    projects: [
        "./**"
    ],
    schemes: [],
    additionalFiles: [
        "./README.md"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
